# Example of a configuration file for MSLP
# Format: <parameter_name> <value>
# You can comment the parameters by using the '#' symbol at the beginning of the line
# Duplicate the file with a new name and modify the parameters as needed
# Add parameters that you want to change from the default values defined in Parameters module'

method_type heur 
method_code mslp
seed 17
greedy_service_order random 
alpha 0.01
threads 1
output_flag_grb_MSLP 0
mslpa 1000
mslpr I
max_time 60
output ./logs/
print_sol 0
solver_method A

