# Example of a configuration file for MIP using Gurobi solver
# Format: <parameter_name> <value>
# You can comment the parameters by using the '#' symbol at the beginning of the line
# Duplicate the file with a new name and modify the parameters as needed
# Add parameters that you want to change from the default values defined in parameters module

method_type form
method_code mip_grb
seed 0
mip_grb_max_time 3600
output_flag_grb_mip 1
max_nodes -2
mip_grb_presolve -1

print_sol 1

# Add which constraints should be active. 
# The range (1-29) is mandatory for this problem.
# No space between characters
constraints_used_mip_str 1-29

# run_callback_mip_gurobi True
# mip_grb_heuristics 0
